### ISSUE TITLE
IO exceptions are ignored

### ISSUE THREAD

**Issue by JanGe** [barrucadu/irc-conduit#3]
I'm currently integrating [`irc-client`](https://github.com/barrucadu/irc-client) into my [`xdcc` utility](https://github.com/JanGe/xdcc) and was wondering, if there is a specific reason why you are ignoring all IO exceptions in [Network/IRC/Conduit.hs:168](https://github.com/barrucadu/irc-conduit/blob/master/Network/IRC/Conduit.hs#L168)?

IMHO from a user's perspective, it would be nice to have `irc-conduit` (and `irc-client` respectively) propagate those errors to calling code, so it can be handled or at least reported.

Any thoughts on this?

**Comment by barrucadu** [comment]
No particular reason that I can remember. I'll change this (and irc-client) today.

**Comment by barrucadu** [comment]
Fixed in irc-conduit-0.2.0.0

**Comment by barrucadu** [comment]
Additionally, irc-client-0.4.0.0 now catches exceptions, disconnect, and then re-throws.
